name: PortalBlocker
version: '1.4'
main: com.noasaba.portalBlocker.PortalBlocker
api-version: '1.21'
commands:
  portalblocker:
    description: PortalBlocker の管理コマンド
    usage: /portalblocker <reload|generateworldconfig>
    permission: portalblocker.admin
permissions:
  portalblocker.admin:
    description: PortalBlocker 管理コマンド実行権限
    default: op
